_drafts/data_challenge_launched.md: 0.5
microlens_submit/microlens-submit/README.md: 1.5
microlens_submit/microlens-submit/README.md,: 1.2
web_resources/rges-pit.github.io/docs/_pages/data_challenge_launched.md: 1.3
