
extensions:
  .py: 1.0
  .md: 0.98
  .rst: 0.9
  .txt: 1.0
  .yaml: 0.9
  .yml: 0.9
  .json: 0.9
  .ipynb: 0.1

path_includes:
  example: 1.1
  tutorial: 1.1
  tests: 1.05
  build: 0.9
  config: 0.9
  README: 1.05